version: "3.9"
#volumes for persist database and redis data
volumes:
  db-data:
    external: false
  redis-data:
    external: false

services:
  nginx:
    build:
      context: .
      dockerfile: ./prod_docker/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
    env_file: ./prod_docker/.env

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build:
      context: .
      dockerfile: ./prod_docker/web/Dockerfile
    env_file: ./prod_docker/.env
    environment:
      RAILS_ENV: production
    depends_on:
      - db
      - redis