version: "3.9"
volumes:
  redis-data:
    external: false
  db-data:
    external: false

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    env_file: .env
    environment:
      RAILS_ENV: production
    ports:
      - "80:80"
    depends_on:
      - db